UIToolTrealet/UIToolTrealet/Controllers/InteractionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIToolTrealet.Data;
using UIToolTrealet.Models;

namespace UIToolTrealet.Controllers
{
    public class InteractionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InteractionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Interactions
        public async Task<IActionResult> Index(int? id)
        {
            int? itemId = id;
            if (itemId == null)
            {
                return NotFound();
            }

            var interactions = await _context.Interaction.Where(m => m.ItemId.Equals(itemId)).ToListAsync<Interaction>();
            if (interactions == null)
            {
                return NotFound();
            }

            ViewData["ItemId"] = id;

            return View(interactions);
        }

        // GET: Interactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interaction = await _context.Interaction
                .Include(i => i.Item)
                .FirstOrDefaultAsync(m => m.InteractionId == id);
            if (interaction == null)
            {
                return NotFound();
            }

            return View(interaction);
        }

        // GET: Interactions/Create
        public IActionResult Create(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId");
                Interaction interaction = new Interaction()
                {
                    ItemId = (int)id,
                };
                return View(interaction);
            }
            return View();
        }

        // POST: Interactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InteractionId,Question,AnswerA,AnswerB,AnswerC,AnswerD,TrueAnswer,ItemId")] Interaction interaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(interaction);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = interaction.ItemId });
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", interaction.ItemId);
            return View(interaction);
        }

        // GET: Interactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interaction = await _context.Interaction.FindAsync(id);
            if (interaction == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", interaction.ItemId);
            return View(interaction);
        }

        // POST: Interactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InteractionId,Question,AnswerA,AnswerB,AnswerC,AnswerD,TrueAnswer,ItemId")] Interaction interaction)
        {
            if (id != interaction.InteractionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InteractionExists(interaction.InteractionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = interaction.ItemId });
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", interaction.ItemId);
            return View(interaction);
        }

        // GET: Interactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interaction = await _context.Interaction
                .Include(i => i.Item)
                .FirstOrDefaultAsync(m => m.InteractionId == id);
            if (interaction == null)
            {
                return NotFound();
            }

            return View(interaction);
        }

        // POST: Interactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int itemId)
        {
            var interaction = await _context.Interaction.FindAsync(id);
            _context.Interaction.Remove(interaction);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = itemId });
        }

        private bool InteractionExists(int id)
        {
            return _context.Interaction.Any(e => e.InteractionId == id);
        }
    }
}

UIToolTrealet/UIToolTrealet/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using UIToolTrealet.Data;
using UIToolTrealet.Models;

namespace UIToolTrealet.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public static IWebHostEnvironment _environment;

        public ItemsController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Items
        public async Task<IActionResult> Index(int? id)
        {
            int? pageId = id;
            if (pageId == null)
            {
                return NotFound();
            }

            var items = await _context.Item.Where(m => m.PageId.Equals(pageId)).ToListAsync<Item>();
            if (items == null)
            {
                return NotFound();
            }

            ViewData["PageId"] = pageId;

            return View(items);
        }



        public async Task<object> generateObjectPage(int? id)
        {
            Page page = await _context.Page.FirstOrDefaultAsync(m => m.PageId == id);


            Dictionary<string, string> objPage = new Dictionary<string, string>();

            objPage.Add("exec", "streamline");
            objPage.Add("pageid", page.PageId.ToString());
            objPage.Add("title", page.Title);
            objPage.Add("desc", page.Desc);
            objPage.Add("opening-hours", page.OpeningHours);
            objPage.Add("exhibition", page.Exhibition);
            objPage.Add("upcoming-events", page.UpcomingEvents);
            objPage.Add("registration-desc", page.RegistrationDesc);
            objPage.Add("buyonline-desc", page.BuyOnlineDesc);
            objPage.Add("banner-src", page.BannerURL);

            // Add từng element
            List<Item> items = await _context.Item.Where(x => x.PageId == page.PageId).ToListAsync();

            List<object> ojbItems = new List<object>();

            foreach (var item in items)
            {
                ojbItems.Add(await generateObject(item));
            }

            var obj = new
            {
                trealet = objPage,
                listItems = ojbItems,
            };

            return obj;

        }



        public async Task<ActionResult> Download(int? id, bool? isPage)
        {
            Item item = await _context.Item.FirstOrDefaultAsync(m => m.ItemId == id);


            int? PageId;
            string nameFile;
            var obj = new object();
            if (isPage == true)
            {
                obj = await generateObjectPage(id);
                nameFile = "streamline-page.trealet";
                PageId = id;

            }
            else
            {
                obj = await generateObject(item);
                nameFile = generateNameFile(item);
                PageId = item.PageId;
            }


            if (obj == null)
            {
                return NotFound();
            }

            string JSONresult = JsonConvert.SerializeObject(obj, Formatting.Indented,
                        new JsonSerializerSettings()
                        {
                            ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                        }
);

            string namePage = PageId.ToString();
            if (PageId == 1)
            {
                namePage = "first";
            }
            else
            {
                namePage = "second";
            }

            string nameFolder = "\\Json\\" + namePage + "page\\";

            // Nếu chưa tạo folder thì tạo folder
            if (!Directory.Exists(_environment.WebRootPath + nameFolder))
            {
                Directory.CreateDirectory(_environment.WebRootPath + nameFolder);
            }



            string path = _environment.WebRootPath + nameFolder + nameFile;

            // Xóa file nếu file đã tồn tại
            if (System.IO.File.Exists(path))
            {
                try
                {
                    System.IO.File.Delete(path);
                }
                catch (Exception ex)
                {
                    //Do something
                }
            }

            // Write that JSON to txt file,  
            System.IO.File.WriteAllText(path, JSONresult);

            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            ViewBag.pathJson = path;
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, nameFile);
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["PageId"] = new SelectList(_context.Item, "PageId", "PageId");
                Item item = new Item()
                {
                    PageId = (int)id,
                };
                return View(item);
            }
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,Title,Desc,TitleImage,PageId")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = item.PageId });
            }
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["PageId"] = new SelectList(_context.Item, "PageId", "PageId", item.PageId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,Title,Desc,TitleImage,PageId")] Item item)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = item.PageId });
            }
            ViewData["PageId"] = new SelectList(_context.Item, "PageId", "PageId", item.PageId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(v => v.Page)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int pageId)
        {
            var item = await _context.Item.FindAsync(id);
            _context.Item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = pageId });
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ItemId == id);
        }

        public async Task<object> generateObject(Item item)
        {
            List<Info> infoes = await _context.Info.Where(m => m.ItemId.Equals(item.ItemId)).ToListAsync<Info>();
            List<Image> images = await _context.Image.Where(m => m.ItemId.Equals(item.ItemId)).ToListAsync<Image>();
            List<Video> videos = await _context.Video.Where(m => m.ItemId.Equals(item.ItemId)).ToListAsync<Video>();
            //List<Interaction> interactions = await _context.Interaction.Where(m => m.ItemId.Equals(id)).ToListAsync<Interaction>();


            List<string> imagesMap = new List<string>();
            List<string> videosMap = new List<string>();
            //List<object> interactionsMap = new List<object>();
            Dictionary<string, string> infoesMap = new Dictionary<string, string>();

UIToolTrealet/UIToolTrealet/Views/Interactions/Create.cshtml
@model UIToolTrealet.Models.Interaction

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo câu hỏi mới</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  class="control-label">CÂU HỎI</label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">TRẢ LỜI A</label>
                <input asp-for="AnswerA" class="form-control" />
                <span asp-validation-for="AnswerA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">TRẢ LỜI B</label>
                <input asp-for="AnswerB" class="form-control" />
                <span asp-validation-for="AnswerB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">TRẢ LỜI C</label>
                <input asp-for="AnswerC" class="form-control" />
                <span asp-validation-for="AnswerC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">TRẢ LỜI D</label>
                <input asp-for="AnswerD" class="form-control" />
                <span asp-validation-for="AnswerD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">ĐÁP ÁN ĐÚNG</label>
                <input asp-for="TrueAnswer" class="form-control" />
                <span asp-validation-for="TrueAnswer" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ItemId" class="form-control" />

            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.ItemId">Trở về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UIToolTrealet/UIToolTrealet/Views/Interactions/Delete.cshtml
@model UIToolTrealet.Models.Interaction

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa câu hỏi</h1>

<h3>Bạn có chắc muốn xóa câu hỏi không?</h3>
<div>
    <h4>Interaction</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            CÂU HỎI
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI A
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerA)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI B
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerB)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI C
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerC)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI D
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerD)
        </dd>
        <dt class = "col-sm-2">
            ĐÁN ÁN ĐÚNG
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrueAnswer)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InteractionId" />
        <input type="hidden" asp-for="ItemId" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-id="@Model.ItemId">Trở về</a>
    </form>
</div>

UIToolTrealet/UIToolTrealet/Views/Interactions/Details.cshtml
@model UIToolTrealet.Models.Interaction

@{
    ViewData["Title"] = "Details";
}

<h1>Chi tiết câu hỏi</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            CÂU HỎI
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI A
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerA)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI B
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerB)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI C
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerC)
        </dd>
        <dt class = "col-sm-2">
            TRẢ LỜI D
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnswerD)
        </dd>
        <dt class = "col-sm-2">
            ĐÁP ÁN ĐÚNG
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrueAnswer)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.InteractionId">Sửa</a> |
    <a asp-action="Index" asp-route-id="@Model.ItemId">Trở về</a>
</div>

UIToolTrealet/UIToolTrealet/Views/Interactions/Edit.cshtml
@model UIToolTrealet.Models.Interaction

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa câu hỏi</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InteractionId" />
            <div class="form-group">
                <label  class="control-label">Câu hỏi</label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Trả lời A</label>
                <input asp-for="AnswerA" class="form-control" />
                <span asp-validation-for="AnswerA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Trả lời B</label>
                <input asp-for="AnswerB" class="form-control" />
                <span asp-validation-for="AnswerB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Trả lời C</label>
                <input asp-for="AnswerC" class="form-control" />
                <span asp-validation-for="AnswerC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Trả lời D</label>
                <input asp-for="AnswerD" class="form-control" />
                <span asp-validation-for="AnswerD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Đáp án đúng</label>
                <input asp-for="TrueAnswer" class="form-control" />
                <span asp-validation-for="TrueAnswer" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ItemId" class="form-control" />

            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.ItemId">Trở về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UIToolTrealet/UIToolTrealet/Views/Interactions/Index.cshtml
@model IEnumerable<UIToolTrealet.Models.Interaction>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách câu hỏi</h1>

<p class="my-3">
    <a asp-action="Create" asp-route-id="@ViewData["ItemId"]"><button type="button" class="btn btn-primary">Tạo câu hỏi mới</button></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                CÂU HỎI
            </th>
            <th>
                TRẢ LỜI A
            </th>
            <th>
                TRẢ LỜI B
            </th>
            <th>
                TRẢ LỜI C
            </th>
            <th>
                TRẢ LỜI D
            </th>
            <th>
                ĐÁP ÁN ĐÚNG
            </th>

            <th>
                THAO TÁC 
            </th>
        </tr>
    </thead>
    <tbody>
        @{ int rowNo = 0; }
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @(rowNo += 1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrueAnswer)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.InteractionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.InteractionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.InteractionId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

@*<div>
    <a asp-area="" asp-controller="Items" asp-action="Index">Trở về</a>
</div>*@