UIToolTrealet/UIToolTrealet/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UIToolTrealet.Models
{
    public class Item
    {
        [Key]
        public int ItemId { get; set; }
        
        public string Title { get; set; }
        public string Desc { get; set; }

        public string TitleImage { get; set; }

        public ICollection<Info> Infoes { get; set; }
        public ICollection<Image> Images { get; set; }
        public ICollection<Video> Videos { get; set; }
        public ICollection<Interaction> Interactions { get; set; }

        public int PageId { get; set; }

        public Page Page { get; set; }
    }
}

UIToolTrealet/UIToolTrealet/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIToolTrealet.Data;
using UIToolTrealet.Models;

namespace UIToolTrealet.Controllers
{
    public class ImagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ImagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Images/5(ItemId)
        public async Task<IActionResult> Index(int? id)
        {
            int? itemId = id;

            if (itemId == null)
            {
                return NotFound();
            }

            var images = await _context.Image.Where(m => m.ItemId.Equals(itemId)).ToListAsync<Image>();
            if (images == null)
            {
                return NotFound();
            }

            ViewData["ItemId"] = id;

            return View(images);
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .Include(i => i.Item)
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Images/Create
        public IActionResult Create(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId");
                Image image = new Image()
                {
                    ItemId = (int)id,
                };
                return View(image);
            }
            
        }

        // POST: Images/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ImageId,Url,ItemId")] Image image)
        {
            if (ModelState.IsValid)
            {
                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = image.ItemId});
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", image.ItemId);
            return View(image);
        }

        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", image.ItemId);
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ImageId,Url,ItemId")] Image image)
        {
            if (id != image.ImageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.ImageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = image.ItemId });
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", image.ItemId);
            return View(image);
        }

        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .Include(i => i.Item)
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int itemId)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = itemId });
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.ImageId == id);
        }
    }
}

UIToolTrealet/UIToolTrealet/Controllers/InfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIToolTrealet.Data;
using UIToolTrealet.Models;

namespace UIToolTrealet.Controllers
{
    public class InfoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InfoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Infoes
        public async Task<IActionResult> Index(int? id)
        {
            int? itemId = id;

            if (itemId == null)
            {
                return NotFound();
            }

            var infos = await _context.Info.Where(m => m.ItemId.Equals(itemId)).ToListAsync<Info>();
            if (infos == null)
            {
                return NotFound();
            }

            ViewData["ItemId"] = id;

            return View(infos);
        }

        // GET: Infoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var info = await _context.Info
                .Include(i => i.Item)
                .FirstOrDefaultAsync(m => m.InfoId == id);
            if (info == null)
            {
                return NotFound();
            }

            return View(info);
        }

        // GET: Infoes/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId");
                Info info = new Info()
                {
                    ItemId = (int)id,
                };
                return View(info);
            }
        }

        // POST: Infoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InfoId,Key,Value,ItemId")] Info info)
        {
            if (ModelState.IsValid)
            {
                _context.Add(info);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = info.ItemId });
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", info.ItemId);
            return View(info);
        }

        // GET: Infoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var info = await _context.Info.FindAsync(id);
            if (info == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", info.ItemId);
            return View(info);
        }

        // POST: Infoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InfoId,Key,Value,ItemId")] Info info)
        {
            if (id != info.InfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(info);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InfoExists(info.InfoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = info.ItemId });
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", info.ItemId);
            return View(info);
        }

        // GET: Infoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var info = await _context.Info
                .Include(i => i.Item)
                .FirstOrDefaultAsync(m => m.InfoId == id);
            if (info == null)
            {
                return NotFound();
            }

            return View(info);
        }

        // POST: Infoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int itemId)
        {
            var info = await _context.Info.FindAsync(id);
            _context.Info.Remove(info);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = itemId });
        }

        private bool InfoExists(int id)
        {
            return _context.Info.Any(e => e.InfoId == id);
        }
    }
}

UIToolTrealet/UIToolTrealet/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIToolTrealet.Data;
using UIToolTrealet.Models;

namespace UIToolTrealet.Controllers
{
    public class PagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pages
        public async Task<IActionResult> Index()
        {
            return View(await _context.Page.ToListAsync());
        }

        // GET: Pages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Page
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Pages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,Title,Desc,OpeningHours,Exhibition,UpcomingEvents,RegistrationDesc,BuyOnlineDesc,BannerURL")] Page page)
        {
            if (ModelState.IsValid)
            {
                _context.Add(page);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Pages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Page.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Pages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PageId,Title,Desc,OpeningHours,Exhibition,UpcomingEvents,RegistrationDesc,BuyOnlineDesc,BannerURL")] Page page)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(page);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Pages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Page
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Pages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var page = await _context.Page.FindAsync(id);
            _context.Page.Remove(page);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
            return _context.Page.Any(e => e.PageId == id);
        }
    }
}

UIToolTrealet/UIToolTrealet/Views/Items/Create.cshtml
@model UIToolTrealet.Models.Item

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo mới đồ vật</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tiêu đề</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mô tả</label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Địa chỉ ảnh đại diện</label>
                <input id="url" asp-for="TitleImage" class="form-control" />
                <span asp-validation-for="TitleImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ảnh từ địa chỉ</label>
                <img id="image"
                     class="rounded d-block" alt="Không có ảnh đại diện" style="max-height: 140px;">
            </div>
            <input type="hidden" asp-for="PageId" class="form-control" />

            <div class="form-group">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.PageId">Trở về</a>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    var lastValue = "";
    document.getElementById("url").onkeyup = function () {
        let inputValue = document.getElementById("url").value;
        if (lastValue != inputValue) {
            document.getElementById("image").setAttribute("src", inputValue);

            lastValue = inputValue;
        }
    }

</script>

UIToolTrealet/UIToolTrealet/Views/Items/Delete.cshtml
@model UIToolTrealet.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa đồ vật</h1>

<h3>Bạn có chắc chắn xóa đồ vật không?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            TIÊU ĐỀ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            MÔ TẢ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class = "col-sm-2">
            ĐỊA CHỈ ẢNH
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TitleImage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ItemId" />
        <input type="hidden" asp-for="PageId" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index"  asp-route-id="@Model.PageId">Trở về</a>
    </form>
</div>

UIToolTrealet/UIToolTrealet/Views/Items/Details.cshtml
@model UIToolTrealet.Models.Item

@{
    ViewData["Title"] = "Details";
}

<h1>Chi tiết đồ vật</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 mb-2">
            TIÊU ĐỀ
        </dt>
        <dd class="col-sm-10 mb-2">
            <h2>@Html.DisplayFor(model => model.Title)</h2>
        </dd>
        <dt class="col-sm-2">
            MÔ TẢ
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class="col-sm-2">
            ĐẠI CHỈ ẢNH ĐẠI DIỆN
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TitleImage)
        </dd>
        <dt class="col-sm-2">
            ẢNH AVA MINH HỌA
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.TitleImage"
                 class="rounded d-block" alt="Không có ảnh đại diện" style="max-height: 140px;">
        </dd>
        <dt class="col-sm-2">
            DANH SÁCH THÔNG TIN THÊM
        </dt>
        <dd class="col-sm-10">
            <a class="nav-link text-dark p-0" asp-area="" asp-controller="Infoes" asp-action="Index" asp-route-id="@Model.ItemId">
                <button type="button" class="btn btn-secondary">Xem danh sách thông tin thêm</button>
            </a>
        </dd>
        <dt class="col-sm-2">
            DANH SÁCH ẢNH
        </dt>
        <dd class="col-sm-10">
            <a class="nav-link text-dark p-0" asp-area="" asp-controller="Images" asp-action="Index" asp-route-id="@Model.ItemId">
                <button type="button" class="btn btn-secondary">Xem danh sách ảnh</button>
            </a>

        </dd>
        <dt class="col-sm-2">
            DANH SÁCH VIDEO
        </dt>
        <dd class="col-sm-10">
            <a class="nav-link text-dark p-0" asp-area="" asp-controller="Videos" asp-action="Index" asp-route-id="@Model.ItemId">
                <button type="button" class="btn btn-secondary">Xem danh sách video</button>
            </a>
        </dd>
        <dt class="col-sm-2">
            DANH SÁCH CÂU HỎI
        </dt>
        <dd class="col-sm-10">
            <a class="nav-link text-dark p-0" asp-area="" asp-controller="Interactions" asp-action="Index" asp-route-id="@Model.ItemId">
                <button type="button" class="btn btn-secondary">Xem danh sách câu hỏi</button>
            </a>
        </dd>

    </dl>
</div>
<div class="my-5"></div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ItemId">Sửa</a> |
    <a asp-action="Index" asp-route-id="@Model.PageId">Trở về</a>
</div>

UIToolTrealet/UIToolTrealet/Views/Items/Edit.cshtml
@model UIToolTrealet.Models.Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa đồ vật</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ItemId" />
            <div class="form-group">
                <label class="control-label">Tiêu đề</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mô tả</label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Địa chỉ ảnh đại diện</label>
                <input id="url" asp-for="TitleImage" class="form-control" />
                <span asp-validation-for="TitleImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ảnh đại diện từ địa chỉ</label>
                <img id="image" src="@Model.TitleImage"
                     class="rounded d-block" alt="Không có ảnh đại diện!" style="max-height: 140px;">
            </div>
            <div class="form-group">
                <a class="nav-link text-dark p-0" asp-area="" asp-controller="Infoes" asp-action="Index" asp-route-id="@Model.ItemId">
                    <button type="button" class="btn btn-secondary">Xem danh sách thông tin thêm</button>
                </a>
            </div>
            <div class="form-group">
                <a class="nav-link text-dark p-0" asp-area="" asp-controller="Images" asp-action="Index" asp-route-id="@Model.ItemId">
                    <button type="button" class="btn btn-secondary">Xem danh sách ảnh</button>
                </a>
            </div>
            <div class="form-group">
                <a class="nav-link text-dark p-0" asp-area="" asp-controller="Videos" asp-action="Index" asp-route-id="@Model.ItemId">
                    <button type="button" class="btn btn-secondary">Xem danh sách video</button>
                </a>
            </div>
            <div class="form-group">
                <a class="nav-link text-dark p-0" asp-area="" asp-controller="Interactions" asp-action="Index" asp-route-id="@Model.ItemId">
                    <button type="button" class="btn btn-secondary">Xem danh sách câu hỏi</button>
                </a>
            </div>
            <input type="hidden" asp-for="PageId" class="form-control" />

            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

    



<div>
    <a asp-action="Index" asp-route-id="@Model.PageId">Trở về</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    var lastValue = "";
    document.getElementById("url").onkeyup = function () {
        let inputValue = document.getElementById("url").value;
        if (lastValue != inputValue) {
            document.getElementById("image").setAttribute("src", inputValue);

            lastValue = inputValue;
        }
    }

</script>

UIToolTrealet/UIToolTrealet/Views/Items/Index.cshtml
@model IEnumerable<UIToolTrealet.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<style>
    .desc-item {
        display: inline-block;
        max-height: 150px;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>


<h1>Danh sách đồ vật</h1>

<p class="my-3">
    <a asp-action="Create" asp-route-id=@ViewData["PageId"]><button type="button" class="btn btn-primary">Tạo đồ vật</button></a>
    <a asp-action="Download" asp-route-id=@ViewData["PageId"] asp-route-isPage="true">Tải về file của Page</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th style="width: 15%;">
                TIÊU ĐỀ
            </th>
            <th style="text-align: center">
                ẢNH ĐẠI DIỆN
                
            </th>
            <th class="w-50">
                MÔ TẢ
            </th>

            <th>
                THAO TÁC
            </th>
        </tr>
    </thead>
    <tbody>

        @{ int rowNo = 0; }

        @foreach (var item in Model)
        {
        <tr>
            <td style="text-align: center">
                @(rowNo += 1)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <img src="@item.TitleImage"
                     class="rounded mx-auto d-block" alt="Không có ảnh đại diện!" style="max-height: 140px;">
            </td>
            <td>
                <div class="desc-item">
                    @Html.DisplayFor(modelItem => item.Desc)
                </div>

            </td>

            <td style="width: 11%; text-align: center" >
                <a asp-action="Edit" asp-route-id="@item.ItemId">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.ItemId">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.ItemId">Xóa</a>
            </td>
        </tr>
        }


    </tbody>
</table>
<div>
    <a asp-area="" asp-controller="Pages" asp-action="Index">Trở về</a>
</div>